# Settings
W_SETTINGS = "settings"
W_FOLDER = "folder"
W_NPAST = "n_past"
W_NFUTURE = "n_future"
W_NDELAY = "n_delay"
W_NFEATURES = "n_features"
W_FEATURES = "features"
W_USEATT = "use_attention"

# Input attention
W_INPUTATT = "input_att"
W_USECAUSAL = "use_causality"
W_CMATRIX = "causal_matrix"
W_CTRAINABLE = "causal_trainable"
W_USECONSTRAINT = "use_causalconstraint"
W_TRAINTHRESH = "causalconstraint_threshold"

# Layers
W_T2V = "time2vect"
W_RNN = "rnn"
W_ENC = "enc_layers"
W_DEC = "dec_layers"
W_UNITS = "units"
W_RSEQ = "return_sequence"
W_RSTATE = "return_state"
W_OUT = "out_dense"
W_DROPOUT = "dropout"
W_ACT = "activation"
W_CNN = "conv_layers"
W_FILTERS = "filters"
W_KSIZE = "kernel_size"